language: cpp
dist: trusty
sudo: required

install: 
  - clang++ -v
  # clang, trunk, from http://llvm.org/docs/LibFuzzer.html#id14
  - ./setup_clang_trunk
  # STL
  - sudo apt-get install -y libc++-dev libc++abi-dev
  # libFuzzer
  - git clone https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer
  - ./Fuzzer/build.sh

script:
  - clang++ -v
  - qmake
  - make
  - ./travis_qmake_clang_cpp17_libfuzzer
  # libFuzzer
  - ./clang++ -std=c++1z -fsanitize=address -fsanitize-coverage=trace-pc-guard test_fuzzer.cc my_functions.cpp libFuzzer.a
  # Will be an error, that must be ignored
  - ./a.out || true
  # If no crash log, Travis will give an error
  - cat crash-*
